version: '3.7'
services:
  tfserving:
    image: tensorflow/serving
    container_name: car-classifier.predictions
    ports:
      - 8501:8501
    networks:
      network-car-classifier:
        aliases:
          - tf_serving
    volumes:
      - ./Data/Model/:/models/resnet_unfreeze_all_filtered/1
    environment:
      - MODEL_NAME=resnet_unfreeze_all_filtered

  explainability:
    image: car-classifier/explainability
    container_name: car-classifier.explainability
    build:
      context: ./car_classifier
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      network-car-classifier:
        aliases:
          - explainability
    volumes:
      - ./Data/Classes/classes.pickle:/models/resnet_unfreeze_all_filtered/1/classes.pickle
      - ./Data/Model/:/models/resnet_unfreeze_all_filtered/1/model

  dashboard:
    image: car-classifier/dashboard
    container_name: car-classifier.dashboard
    depends_on:
      - nginx
      - tfserving
      - explainability
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    networks:
      - network-car-classifier
    environment:
      - IS_IN_DOCKER=True
    restart: on-failure

  nginx:
    image: nginx
    container_name: car-classifier.webserver
    ports:
      - 1234:80
    networks:
      network-car-classifier:
        aliases:
          - nginx
    volumes:
      - ./Data/Images/:/usr/share/nginx/html:ro
      - ./dashboard/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  network-car-classifier:
    name: network-car-classifier